import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '@/components/Header';
import "./globals.css";
import NavMobile from "@/components/NavMobile";
import Hero from "@/components/Hero";
import { TravelProvider } from "@/contexts/TravelContext";
import Footer from "../components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                style={{minHeight: '100vh'}}
            >
                <Navbar />

                <Hero />
                <TravelProvider> {children} </TravelProvider>
                <NavMobile />
                
                <Footer />
            </body>
        </html>
    );
}
