# Generated by Django 5.2 on 2025-06-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrainCooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrainRouteEdge',
            fields=[
                ('route_edge_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('destination_city', models.CharField(blank=True, max_length=25, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=25, null=True)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainTravel',
            fields=[
                ('travel_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_travels', to='train.traincooperative')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_travels', to='train.trainroute')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_travels', to='train.train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainTicket',
            fields=[
                ('ticket_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('campartment_no', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_no', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to='train.traintravel')),
            ],
        ),
    ]
