# Generated by Django 5.2 on 2025-06-04 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compartment_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('compartment_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainCooperative',
            fields=[
                ('cooperative_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('route_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('origin_city', models.CharField(blank=True, max_length=25, null=True)),
                ('dest_city', models.CharField(blank=True, max_length=25, null=True)),
                ('edge_identifiers', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainRouteEdge',
            fields=[
                ('route_edge_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('origin_city', models.CharField(blank=True, max_length=25, null=True)),
                ('dest_city', models.CharField(blank=True, max_length=25, null=True)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainTravel',
            fields=[
                ('travel_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_travels', to='train.traincooperative')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_travels', to='train.trainroute')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_travels', to='train.train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainTicket',
            fields=[
                ('ticket_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('campartment_no', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_no', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to='train.traintravel')),
            ],
        ),
    ]
