# Generated by Django 5.2 on 2025-08-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_ticket_birth_date_ticket_first_name_ticket_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='campartment_no',
            new_name='compartment_no',
        ),
    ]
