# Generated by Django 5.2 on 2025-08-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_ticket_birth_date_ticket_first_name_ticket_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='capacity',
        ),
        migrations.AddField(
            model_name='travel',
            name='reserved_compartments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travel',
            name='reserved_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
