# Generated by Django 5.2 on 2025-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_remove_travel_capacity_travel_reserved_compartments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='capacity',
            field=models.IntegerField(blank=True, help_text="If left empty, it will be set to the train's capacity automatically.", null=True),
        ),
    ]
