# Generated by Django 5.2 on 2025-08-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_travel_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='reserved_compartments',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='reserved_seats',
        ),
        migrations.AddField(
            model_name='ticket',
            name='get_full_compartment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travel',
            name='seat_stat',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
