# Generated by Django 5.2 on 2025-08-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_remove_travel_reserved_compartments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='campartment_no',
            new_name='compartment_no',
        ),
    ]
