# Generated by Django 5.2 on 2025-08-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
