# Generated by Django 5.2 on 2025-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_ticket_birth_date_ticket_first_name_ticket_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='seat_stat',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='capacity',
            field=models.IntegerField(blank=True, help_text="If left empty, it will be set to the airpalne's type capacity.", null=True),
        ),
    ]
