# Generated by Django 5.2 on 2025-09-15 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vip', 'VIP'), ('man-vip', 'MAN-VIP'), ('classic', 'CLASSIC')], default='VIP', max_length=50)),
                ('seat_count', models.PositiveIntegerField(blank=True, help_text="If left empty, it will be set to the bus's type capacity.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('cooperative_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^0\\d{10}$')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminal_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^0\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('travel_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=25, null=True)),
                ('dest', models.CharField(blank=True, max_length=25, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('capacity', models.IntegerField(blank=True, help_text="If left empty, it will be set to the bus's type capacity.", null=True)),
                ('seat_stat', models.JSONField(blank=True, default=dict, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='bus.bus')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='bus.cooperative')),
                ('dest_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_travels', to='bus.terminal')),
                ('org_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_travels', to='bus.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('seat_no', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1, null=True)),
                ('payment_due_datetime', models.DateTimeField(blank=True, null=True)),
                ('canceled', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bus.travel')),
            ],
        ),
    ]
