# Generated by Django 5.2 on 2025-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_count',
            field=models.PositiveIntegerField(blank=True, help_text="If left empty, it will be set to the bus's type capacity.", null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('vip', 'VIP'), ('man-vip', 'MAN-VIP'), ('classic', 'CLASSIC')], default='VIP', max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='capacity',
            field=models.IntegerField(blank=True, help_text="If left empty, it will be set to the bus's type capacity.", null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='seat_stat',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
